name: Publish Website to CPanel (QA Verify)
on:
  push:
    branches:
      - qa
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.QA_FTP_SERVER }}
        username: ${{ secrets.QA_USERNAME }}
        password: ${{ secrets.QA_PASSWORD }}
